### ISSUE TITLE
[아이템 24] private 정적 멤버 클래스 (예시 Map)

### ISSUE THREAD

**Issue by Leeyerimearth** [prgrms-web-devcourse/BE-Team-preArmand-Book-study#15]
148p. 두번째 문단의 예시가 이해가 가지 않습니다. 혹 이해하신 분이 계시다면 설명을 부탁드릴 수 있을까요?
추가로, 책에서 말하는 엔트리를 Map 구현체의 인스턴스로 이해했는데 잘못 이해하고 있는걸까요?

> 따라서 엔트리를 비정적 멤버클래스로 표현하는 것은 낭비이고, private 정적 멤버 클래스가 가장 알맞다. 엔트리를 선언할 때 실수로 static을 빠뜨려도 맵은 여전히 동작하겠지만, 모든 엔트리가 바깥 맵으로의 참조를 갖게되어 공간과 시간을 낭비할 것이다.

해당 문장 앞부분의 내용은 하기와 같이 이해했습니다.

> 키와 값을 매핑시키는 Map인스턴스를 생각해보자. 많은 Map 구현체는 각각의 키-값 쌍을 표현하는 엔트리 객체들을 가지고 있다. 모든 엔트리가 맵과 연관되어 있지만 엔트리의 메서드들(getKey, getValue, setValue)은 맵을 직접 사용하지는 않는다.

- 이해한내용 : Map 구현체 (HashMap, TreeMap, LinkedHashMap)는 여러 객체들을 가지고있고, 실제 HashMap클래스 코드를 보면 getKey, getValue, setValue는 내부에서만 쓰이고 인스턴스 메서드로 직접 호출이 불가하다.

**Comment by epicblues** [comment]
getKey,getValue 메서드들을 직접 사용해 보면서 삽질한 기억이 있어서 이 부분부터 코드로 확인해 봤어요! 

```java
 var map = Map.of("k1","v1","k2","v2");
    map.entrySet().forEach(entry -> {
      entry.getKey(); // "k1", "k2" 
      entry.getValue(); // "v1", "v2"
    });
```

### 두 번째 문단 관련

제가 알기로는 만약 entry 가 비정적 멤버인데, 
이 entry를 사용하고 메모리에서 해제하지 않았을 때
 문제가 생기는 것으로 알고 있습니다!

entry가 비정적 클래스일 경우, entry 인스턴스가 생성될 때 부모 클래스의 인스턴스에 대한 참조를 갖고 있습니다.

entry가 정적 멤버 클래스이므로 다른 예시를 들자면 이런 식으로요!


![image](https://user-images.githubusercontent.com/19306609/164735593-7e482f08-8dc8-4101-8d65-73e35b2c6b5a.png)


entry에 대한 참조를 해제하지 못할 경우(다른 컬렉션에 넣거나 등) entry가 참조하고 있는 
부모 클래스 인스턴스(Map) 또한 가비지 컬렉션 대상에서 제외되어 메모리에 상주하게 됩니다.
Map이 많은 메모리를 차지할 경우 추후에 문제가 발생할 수 있기 때문에 처음부터 정적 멤버 클래스로 만들라고 한 것 같습니다.

정확하진 않으므로 틀린 부분 있으면 다른 분들이 지적해주세요!!!!!!☠️☠️☠️☠️
