### ISSUE TITLE
[아이템 33] Annotation 관련

### ISSUE THREAD

**Issue by epicblues** [prgrms-web-devcourse/BE-Team-preArmand-Book-study#16]
> 204페이지 최상단 예시
```java
public <T extends Annotation>
    T getAnnotation(Class<T> annotationType)
```

이 코드의 의미를 이해하지 못하겠습니다! AnnotatedElement에 붙어 있는 에너테이션들 중에서 T 타입의 에너테이션 인스턴스만 가져오라는 함수인가요?

**Comment by Leeyerimearth** [comment]
제가 이해한 버전은
getAnnotation은 매개변수로 
1. 클래스리터럴(Integer.class or String.class등 근데 저 메서드에선 이제 Annotation.class 혹은 그 하위타입만 가능)을 받는데, 
2. 이 클래스 리터럴은 Annotation 클래스와 그 하위클래스들만 받는다.
3. 리턴값은 매개변수로 받은 타입의 인스턴스를 리턴한다.

로 이해했어요.

**Comment by HunkiKim** [comment]
저도 예림님처럼 이해했습니다.
