### ISSUE TITLE
[아이템 34] 열거 타입에 새로운 상수를 추가하거나 순서를 바꿔도 다시 컴파일 하지 않아도 된다.

### ISSUE THREAD

**Issue by epicblues** [prgrms-web-devcourse/BE-Team-preArmand-Book-study#18]
> 210 페이지 세번째 문단

* 다시 컴파일하지 않아도 된다는 것은 클라이언트 클래스를 말하는 건가요? 
*  클라이언트 클래스가 컴파일 될 때 정수 열거 패턴에서는 실제 값이 저장되는 반면, 열거 타입은 열거 타입 주소(?)를 저장하고 있기 때문에 열거 타입 내부를 변경해도 클라이언트 클래스는 상관이 없다는 말일까요?

**Comment by kimziou77** [comment]
**☠️ 답변아니고 같이 하소연 하는 글입니다 ☠️** 

저도 해당 부분 이해 잘 안가서 체크해놓았는데

219 페이지 마지막 줄

> 열거타입은 나중에 상수가 추가돼도 바이너리 수준에서 호환되도록 설계되었다. 

저번에도 비슷한 이슈가 있었지만 바이너리 수준과 연관되어 있지 않을까 생각합니다..

근데 이런 경우가 실제로 어떻게 일어나는지 감이 오질 않네요..
실무의 어떤부분과 연관될 수 있을까요...?

**Comment by yuminhwan** [comment]
저도 민성님처럼 이해했습니다! 

> 공개되는 것이 오직 필드의 이름뿐이라, 정수 열거 패턴과 달리 상수 값이 클라이언트로 컴파일되어 각인되지 않기 때문이다. 

이름만 공개되고 내부값은 숨겨져있기 때문에 정수 열거 패턴을 썼을 때와 달리 컴파일을 할 필요가 없는 것 같아요!
아마 #13 이때 말했던 바이너리쪽 이야기 인 것 같습니다.

**Comment by epicblues** [comment]
https://community.oracle.com/tech/developers/discussion/1545057/whats-the-difference-between-a-symbolic-reference-and-direct-reference%5D

참고해서 추가적으로 적습니다. enum도 레퍼런스 타입이므로 아래 설명에 포함될 것 같습니다. 자세한 내용은 위 링크 참조하세요!

컴파일 됐을 때 레퍼런스 타입은 Symbolic Reference(고유한 문자열 이름)로 보관된다.
프로그램이 실행되고 jvm이  symbolic reference를 처음 읽을 때, 해당 타입의 direct reference(pointer or offset)를 찾아내고(없을 경우 load하고) 이 연결 관계를 자료구조에 저장한다..(Dynamic LInking)
이후 같은 symbolic reference를 jvm이 읽을 때, 자료구조에 캐싱된 연결을 참고하여 direct reference를 사용한다.
