### ISSUE TITLE
[아이템34] Enum의 가장 좋은 사용법이 무엇이고 왜 그게 좋은 사용법인가요?

### ISSUE THREAD

**Issue by kimziou77** [prgrms-web-devcourse/BE-Team-preArmand-Book-study#19]
저는 궁금합니다. 제곧내..

Enum을 태그처럼 쓸 수 있는데,
아이템 23 태그달린 클래스보다는 계층 구조를 활용하라고 나와있습니다.

하지만 Enum을 쓰게 되면 결국 Enum값마다 if문이나 Switch문이 쓰이게 됩니다.

211p 코드 34-3을 보면 다음 예제가 있는데
![image](https://user-images.githubusercontent.com/41179265/166630333-00d12b98-0b74-48b7-8eec-006dc492b016.png)
얘도 Planet을 상속받는 각 클래스로 만드는것이 가능할텐데
Enum으로 관리하는 것에 무슨 의의가 있는지 궁금합니다.

책에서 나온 열거타입을 쓰는 경우는 다음과 같습니다.

**본질적으로 열거 타입인 타입**
- 태양계 행성
- 한 주의 요일
- 체스말

**허용하는 값 모두를 컴파일 타임에 이미 알고 있을 때**
- 메뉴 아이템
- 연산 코드
- 명령줄 플래그

이들이 왜 Enum으로 쓰기 좋은 코드인지 의논하고 싶습니다.

추가로 + 이넘과 전략패턴을 같이 쓰는 방법? 이것도 잘 이해가 안갑니다ㅠㅠ

**Comment by yuminhwan** [comment]
Planet 같은 경우 질량이나 반지름이 **변하지 않고 고정되어 있는 값**이니 Enum을 활용하는 것이 더 좋아보입니다. 
각 클래스로 만들 경우 하위 클래스들은 그저 값만 넣어주는 클래스가 될 것 같습니다!
토요일날 좀 더 의견 나눠보면 좋을 것 같네요~~ ( 전략패턴 관련해서도요! )

**Comment by epicblues** [comment]
저는 enum을 쓰는 이유를 계산기 미션 때 민환님의 코드를 참조(?)해서 Operator Enum으로 해결했던 일이 떠올랐습니다. 

 ```java
public enum Operator {


	ADDITION('+', Double::sum),
	SUBTRACTION('-', (a, b) -> a - b), 
    MULTIPLICATION('*', (a, b) -> a * b),
	DIVISION('/', (a, b) -> a / b);

// if-else, switch 대체
public static Operator from(char candidate)  {
		for (Operator operator : Operator.values()) {
			if (operator.signature == candidate) {
				return operator;
			}
		}
		throw new WrongOperatorTokenException();
	}
public double operate(double a, double b) {
		return concreteOperator.apply(a, b);
	}
```
 * enum의 정적 메서드인 values()를 이용해서 적합한 Operator 상수를 찾아내는 방식이 저는 if -else를 대체한다고 생각이 들었습니다.

 * 클라이언트 코드에서 from(char candidate) 메서드를 통해 Operator를 받고, 그 Operator를 실행 시키는 코드에서 전략 패턴을 사용한다고 생각했습니다. 
```java
String candidate = bufferedReader.readLine();
Operator operator = Operator.from(candidate);
// 전략 패턴?! 실제로 어떤 연산이 실행될 지는 런타임에 알 수 있습니다.
operator.operate();
```

**Comment by Leeyerimearth** [comment]
**enum type이 형성된 이유 자체가** 사용목적이라고 생각합니다.
아이템 34장 시작 처음 내용에, 정수 열거 패턴의 대안을 제시한 것이 Enum Type이라고 하였으니
**정수 상수 나열의 사용을 대체하는것이 enum의 사용 목적이라고 생각합니다.**

 enum type의 추가 장점에 대한 개인적의견으로는.. 
1. 클래스보다 만드는 과정이 더 편리할 것같습니다. (예시가 카드이고 상속 클래스로 구현한다고 하면, 클래스를 52개(맞나요?) 만들어야하지만 열거타입을 이용하면 하나의 enum 클래스로 만들 수 있음)
2. 클래스보다는 enum 한곳에 모아둘 수 있어 관리하기 용이함.
3. 확장을 막고 enum에 명시된 애들 외의 값은 허용하지 않는다는 명확함

등이 있을 것 같습니다.
