### ISSUE TITLE
[아이템 15] 테스트만을 위해 클래스, 인터페이스, 멤버를 공개 API로 만들어서는 안 된다.

### ISSUE THREAD

**Issue by epicblues** [prgrms-web-devcourse/BE-Team-preArmand-Book-study#2]
🖐️  위치 : 99 페이지 첫 번째 문단

> 책과 살짝(?)벗어난 내용이지만 호기심에 여쭤봅니다!

다들 테스트 코드 작성하실 때 private 메서드와 관련된 테스트도 작성하시는지 궁금합니다! 
만약 하신다면 어떤 방법으로 하시는 지도요! 
저는 '하면 좋을 것 같은데 방법이 까다로워서, 테스트 코드가 역으로 개방-폐쇄 원칙을 저해할 것 같다.' 
라고 생각합니다.

인터넷에서 살짝 조사를 해본 결과 이런 의견들이 있네요

## 테스트 해야 한다.
1. 특정 테스트가 실패 했을 때 어디에서 문제가 발생했는지 구체적으로 잡아 준다.
2. 테스트가 주는 효용(견고한 코드를 작성하고 있다는 확신, test coverage 100%!)이 커진다.

## 테스트 하지 말아야 한다.
1. 내부 구현을 드러내기 때문에 캡슐화를 깬다.
2. 만약에 테스트 대상의 매우 중요한 기능이 private 메서드로 되어 있으면, 차라리 다른 클래스로 분리해서 public 인터페이스로 바꾼 뒤에 테스트 해라. 
  <code>(private 메서드 테스트하고 싶다  == 리팩터링 해야 한다!)</code>
4. 유닛 테스트 자체와 테스트 대상과의 결합도가 높아진다.
5. 충분한 edge case를 설정하고 public 인터페이스를 테스트 하면 private method도 꼼꼼하게 확인할 수 있다.

관련 링크
https://stackoverflow.com/questions/105007/should-i-test-private-methods-or-only-public-ones

**Comment by epicblues** [comment]
mic check one two

**Comment by epicblues** [comment]
hello

**Comment by yuminhwan** [comment]
저는 테스트를 할 필요가 없다고 생각합니다. 어차피 public메서드 테스트 시에 같이 테스트가 된다고 느끼기에 굳이 해야할 필요가 있나 싶습니다. 
대신 private 메서드를 사용하는 public 메서드 테스트가 private메서드를 커버를 해야 겠죠.

하지만 개발자마다 다 의견이 다른 것 같습니다. 굳이 private로 만들지 말고 package-private로 만든 후 테스트하자는 개발자도 있고 엄격하게 private로 설정해야 한다는 사람도 있고 정답은 없다고 생각합니다. 

아만드 멘토님이 코드 리뷰때 남겨주신 코멘트와 도움 되실 만한 링크 첨부하겠습니다.
> 테스트코드 역시 관리의 대상이기 때문에 많으면 좋긴 하지만 그만큼 관리가 힘들어질 수 있습니다. 그러하기에 Private 메소드 테스트는 직접적으로 하는게 아닌 그 private 메소드를 사용하는 메소드의 테스트 케이스에서 커버를 해줘야 한다고 생각합니다. 그렇기에 private 메소드를 커버하는 테스트코드를 다양한 값을 통해 테스트해서 검증 할 필요가 있다고 생각합니다.

- https://www.slipp.net/questions/253

**Comment by Leeyerimearth** [comment]
이번 과제를 하면서 private 메서드도 테스트 해보고 싶은것이 있었지만 테스트 하지 못했습니다. 2주차 과제에서는 테스트를 한번 시도해보려고 합니다.
다만 1주차때 관련해서 찾아본 글에서는 private 메서드는 굳이 따로 테스트하지 않으나(사용하는 public 메서드가 private 내용을 충분히 커버가능하다는 전제하에) 만약 테스트가 꼭 필요해지는 케이스라면 로직설계를 잘못한것은 아닌지 확인해보라고 하더라구요. 제 Spring 1주차 과제가 이 케이스에 해당하는 것 같습니다.. ㅎㅎ;;
