### ISSUE TITLE
[아이템34] 열거 타입 상수 맵 

### ISSUE THREAD

**Issue by yuminhwan** [prgrms-web-devcourse/BE-Team-preArmand-Book-study#20]
> P.216
하지만 열거 타입 상수는 생성자에서 자신의 인스턴스를 맵에 추가할 수 없다. 이렇게 하려면 컴파일 오류가 나는데, 만약 이 방식이 허용되었다면 런타임에 NullPointerException이 발생했을 것이다. 열거 타입의 정적 필드 중 열거 타입의 생성자에서 접근할 수 있는 것은 상수 변수 뿐이다 (아이템 24)

생성자에서 열거 타입 상수를 추가할 수 없는 이유가 그저 생성자가 실행되는 시점에는 정적 필드가 아직 초기화 되기 전이기 때문인가요?
여기서 말하는 정적 필드가 Map을 뜻하는 게 맞을까요??

**Comment by epicblues** [comment]
저도 말씀하신 것으로 이해했습니다!

생성자 실행 -> enum 상수 인스턴스 등록 -> 정적 필드 초기화 코드 실행

JVM이 생성자 코드를 실행하는 시점에서는 정적 필드 초기화 코드를 실행하지 않는 상태고, 따라서 Map이 null 상태이기 때문에 NullPointerException을 발생시키는 것으로 봤어요!

**Comment by yuminhwan** [comment]
찾아보니 
1. Enum의 primitive type 상수 : `final`, `static final` 
2. Enum의 생성자 
3. Enum의 static 변수 : `static Map`
이런식으로 진행되는 것 같군요. 
상수라서 `static final`만 허용될지 알았는데 그냥 `final`로 지정해도 되긴 하네요.

```java
public enum PayrollDay {
    PLUS (1),
    MINUS(2);

    private final int value;
    private final int test = 1;

    PayrollDay(int value) {
        this.value = value;
        System.out.println("test = " + test);
    }

    public static void main(String[] args) {
        System.out.println(PLUS.value);
    }
}
=================================
출력 결과 
test = 1 
test = 1 
1
```

추가적으로 JVM에서 클래스 로드시 정적 필드가 코드에 나타나는 순서대로 초기화된다고 합니다. 
결국 이넘 내부의 값들도 선언되는 순서가 역전되면 참조할 수 없게 됩니다! 
위의 예제에서 MINUS는 PLUS를 참조할 수 있지만 PLUS는 MINUS를 참조할 수 없게 됩니다.

그래서 Enum은 항상 정적 필드가 enum 상수보다 먼저 초기화되지 못하도록 보장합니다.
<img width="631" alt="스크린샷 2022-05-07 오전 12 59 01" src="https://user-images.githubusercontent.com/65746780/167170713-612732c8-dc67-468e-abad-d0d6cf9fd4a0.png">



찾아보니 책의 방식말고 inner class를 사용하는 방법도 있네요! 
```java
enum Day {

    private static final class Helper {
        static Map<String,Day> ABBR_TO_ENUM = new HashMap<>();
    }

    Day(String abbr) {
        this.abbr = abbr;
        Helper.ABBR_TO_ENUM.put(abbr, this);

    }

    public static Day getByAbbreviation(String abbr) {
        return Helper.ABBR_TO_ENUM.get(abbr);
    }
}
```
해당 방법이 가능한 이유는 아마 ABBR_TO_ENUM를 사용할 때 초기화가 진행되기 때문에 사용이 가능해보이긴 하는 데 잘 모르겠네요 ㅠㅠ 
이야기해보면 좋을 것 같습니다.

**Comment by Leeyerimearth** [comment]
enum 내부의 값들이 순서를 갖게되는 것도 ordinal() 이렇게해서 가지고 올 수 있는 걸 보면 알 수 있을 것 같습니다 !

그러면 결국 민환님이 최초에 해주신 질문, 즉 생성자에서 자신의 인스턴스를 맵에 추가 할 수 없는 이유는
생성자에서는 아직 static 변수까지 다 초기화되지 않았으니 ! 인스턴스 생성(?) 초기화(?)가 완료되지 않았으니로 이해할 수 있을까요?
