### ISSUE TITLE
정수는 열거 타입과 다르게 타입 안전하지 않다?

### ISSUE THREAD

**Issue by HunkiKim** [prgrms-web-devcourse/BE-Team-preArmand-Book-study#21]
타입 안전하지 않다는게 정확히 어떤말인가요? 같은 타입이라 값이 다른 의미를 지녀도 같은 값이기 때문에 안전하지 않다는건가요? Enum할 때 계속 나오는데 잘 모르곘네요..

**Comment by yuminhwan** [comment]
### 주의! 뇌피셜입니다.
저도 훈기님이 말씀하신 대로 이해했습니다. 
정수로 사용하게 되면 다른 의미일때 그저 이름으로만 구분하지 실제 값으로는 구분하지 못하기 때문에 타입 안전을 보장할 수 없다고 나온 것 같습니다.
책의 예제에서 오렌지 상수와 사과 상수가 타입이 다르지만 그저 정수 상수이기 때문에 오렌지가 사용되어야 할 곳에 사과가 사용되어도 아무 문제없어 타입이 안전하지 않다고 한 것 같습니다.

**Comment by Leeyerimearth** [comment]
저도 훈기님 민환님과같이 이해했습니다 ! 
컴파일러는 실제 **정수 값** 만을 확인하지 사과 타입인지 오렌지 타입인지 확인이 불가능하기때문에 
타입 안전을 보장할 수 없다고 한 것으로 이해했습니다.
