### ISSUE TITLE
[아이템 42] 열거 타입 생성자 안의 람다는 열거 타입의 인스턴스 멤버에 접근할 수 없다.

### ISSUE THREAD

**Issue by epicblues** [prgrms-web-devcourse/BE-Team-preArmand-Book-study#22]
page 257 밑에서 8번째 줄

> 열거 타입 생성자에 넘겨지는 인수들의 타입도 컴파일 타임에 추론된다. 따라서 열거 타입 생성자 안의 람다는 열거 타입의 인스턴스 멤버에 접근할 수 없다. 따라서 상수별 동작을 단 몇 줄로 구현하기 어렵거나, 인스턴스 필드나 메서드를 사용해야만 하는 상황이라면 상수별 클래스 몸체를 사용해야 한다.

1. 생성자로 넘겨지는 람다의 타입은 컴파일 타임에 추론된다.
2. 따라서 열거 타입 생성자 안의 람다는 열거 타입 인스턴스 멤버에 접근할 수 없다. (?)

는 책의 문장 전개가 이해가 되지 않습니다! 😒. 

`컴파일 타임에 추론된다`는 것은 enum에서 선언한 필드 타입과 제가 생성자의 인수로 작성한 람다의 타입이 일치하지 않을 때 IDE에서 경고를 보여주는 것 같은 상황이나, 억지로 컴파일을 했을 경우 컴파일러에서 아래와 같은 에러를 던지는 것을 떠올리면서 이해했는데.
```
java: incompatible types: bad return type in lambda expression
    java.util.UUID cannot be converted to org.programmers.devcourse.voucher.engine.voucher.entity.Voucher, 
```
이것이 인스턴스 멤버에 접근할 수 없는 이유가 되는지는 잘 모르겠습니다.

아니면 제가 떠올린 예시가 잘못된 걸까요?

**Comment by yuminhwan** [comment]
### 주의! 뇌피셜입니다

저 같은 경우에는 `컴파일 타임에 추론된다.`를 컴파일타임에 초기화? 완성? 된다고 생각했습니다. 
인스턴스 멤버의 경우 생성자 이후에 초기화되니 접근할 수 없는 게 아닐까 라고 생각합니다!!
대신 상수별 클래스 몸체는 생성자에서 초기화되는 것이 아니니 사용할 수 있는 것 같습니다.

- 클래스 몸체 
<img width="631" alt="스크린샷 2022-05-13 오후 6 26 28" src="https://user-images.githubusercontent.com/65746780/168254532-96672f97-bc3b-4f85-bac1-3f7cc27fcf18.png">

<br>

- 람다
<img width="540" alt="스크린샷 2022-05-13 오후 6 27 46" src="https://user-images.githubusercontent.com/65746780/168254548-14f4bd14-f1fa-461f-b987-2dc05801e594.png">

**Comment by kimziou77** [comment]
☠️
자세한 메모리 할당 순서나 이런 부분은.. 없고 제가 생각한 내용이라
설명이 추상적일 수 있는데.. **패러다임이 다르다는 문제가 아닐까 생각**   해봅니다

이번장의 주제인 함수형 인터페이스, 람다 이런 개념들이
객체보다는 함수형 프로그래밍의 패러다임을 가지고 가기 때문이지 않을까.. 

```
람다는 작은 함수 객체를 아주 쉽게 표현할 수 있어 (이전 자바에서는 실용적이지 않던) 함수형 프로그래밍의 지평을 열었다.
                                                                         - 이펙티브자바 258p 핵심정리
```

---

그래서 함수형 프로그래밍의 패러다임을 가져가는 것과, 람다에서 외부 변수 접근이 안되는 이유로 생각한 부분은
```
*클로저와 자바 프로그램 사이의 극단적인 차이로는,  (*클로저는 함수형 언어 중 하나이다)
자바 프로그램은 가변 변수를 사용하는데
가변변수는 프로그램 실행중에 상태가 변할 수 있다. 
클로저에서는 변수가 한번 초기화 되면 절대로 변하지 않는다.
이는 우리에게 놀라운 사실을 알려준다. 함수형 언어에서 변수는 변경되지 않는다.
                                       - 클린아키텍처 55p
```
위 글에 있는 `함수형 언어에서 변수는 변경되지 않는다` 이 부분에서
자바 람다식에서 외부에 있는 변수들을 사용하지 못하게 막는것이 아닐까..! 생각합니다..
