### ISSUE TITLE
자바하면 객체지향 프로그래밍인데, 함수형 프로그래밍의 지평을 열은게 왜 좋은걸까?

### ISSUE THREAD

**Issue by kimziou77** [prgrms-web-devcourse/BE-Team-preArmand-Book-study#23]
라는 의문을 가졌었고
이에 대한 의문점을 찾기위해서 조사해보았습니다

그리고 다음 블로그의 첫 문장에서 뼈를 맞아버렸습니다. ⚡ 

[자바 8에서 왜 함수형 프로그래밍이 도입되었을까?](https://tecoble.techcourse.co.kr/post/2021-09-30-java8-functional-programming/)

그리고 돌이켜보면 너무 객체지향만을 선호하며 객체지향만이 정답이야!를 외치며 살았던 것 같네요.
함수형 프로그래밍 뭔지모르겠당~~ 어려운데 나랑은 상관없는 일이겠지~ 하고 종종 가볍게 넘기고는 했었는데
함수형 프로그래밍에 대해서도 다시 한 번 생각해봐야 겠네요 하하호호

**Comment by epicblues** [comment]
잘 읽었습니다.
Optional이 함수평 프로그래밍에서 고안해낸 개념인 줄 몰랐네요!
