### ISSUE TITLE
[아이템 55] 옵셔널 반환은 신중히 하라 329p

### ISSUE THREAD

**Issue by kimziou77** [prgrms-web-devcourse/BE-Team-preArmand-Book-study#27]
329p 첫 문단에

이따금 기본값을 설정하는 비용이 아주 커서 부담이 될 때가 있다. 
그럴때는 Supplier<T>를 인수로 받는 orElseGet을 사용하면,
값이 처음 필요할때 Supplier<T>를 사용해 생성하므로 초기 설정 비용을 낮출 수 있다.
(사실 이 메서드는 compute로 시작하는 Map 메서드들과 밀접하니 orElseCompute로 이름짓는게 더 나았을지도 모르겠다)

이 부분이 어렵게 느껴집니다 T T
혹시 이해하신 분 계신가요?-?
HELP!! 도와줘요 pre아만드!!

**Comment by yuminhwan** [comment]
`orElse(T other)`의 경우 Optional의 값과 관계없이 무조건 실행되고 `orElseGet(Supplier<? extends T> other)`의 경우 Optional의 값이 비어있을 때만 실행됩니다.
그렇기 때문에 기본값 설정하는 비용이 매우 클 때 orElse를 사용하게 되면 항상 생성하게 되니 orElseGet을 사용하라고 하는 것 같습니다. 
- https://ysjune.github.io/posts/java/orelsenorelseget/
```java
@DisplayName("orElse는 Optional의 값과 상관없이 실행된다.")
@Test
void orElse() {
    // given
    Post post = createPost();
    postRepository.save(post);

    // when
    Post findPost = postRepository.findById(post.getId())
        .orElse(postRepository.save(createPost()));

    // then
    assertThat(postRepository.count()).isEqualTo(2L);
}

@DisplayName("orElseGet는 Optional의 값이 비어있을 때만 실행된다.")
@Test
void orElseGet() {
    // given
    Post post = createPost();
    postRepository.save(post);

    // when
    Post findPost = postRepository.findById(post.getId())
        .orElseGet(() -> postRepository.save(createPost()));

    // then
    assertThat(postRepository.count()).isEqualTo(1L);
}
```

<br> 

Map관련내용은 `computeIfAbsent()` 나 `computeIfPresent()`와 같은 메서드 때문에 말하고 있는 것 같습니다. 
- https://blog.advenoh.pe.kr/java/자바8-HashMap-보다-간결하고-효과적으로-작성하기/

**Comment by epicblues** [comment]
민환님 설명에 잡지식(?)을 덧붙이자면
Optional의 `orElseThrow()` 도` Supplier`를 활용하게 되는데 

그 이유는 [예외 생성 비용이 커서](http://java-performance.info/throwing-an-exception-in-java-is-very-slow/) 그런 것이라 하네요! 
요약하자면 stack trace를 작성하는 동작이  부담이 많이 된다고 하네요.
