### ISSUE TITLE
[아이템 15] 질문모음

### ISSUE THREAD

**Issue by HunkiKim** [prgrms-web-devcourse/BE-Team-preArmand-Book-study#5]
# 질문
1. 캡슐화가 여러 컴포넌트를 병렬로 개발할 수 있는이유가 궁금합니다! (96P 아래)
2. package-private로 선언하면 내부구현이 되어 언제든 수정 가능하고, public은 하위 호환을 위해 영원히 관리해줘여한다.(97P 중간) 이 부분에서 내부구현이 된다고 수정가능한 이유와 하위 호환이라는 단어가 어떤 의미인지 궁금합니다.
3. 해당 클래스가 표현하는 추상 개념을 완성하는 데 꼭 필요한 구성요소로써의 상수라면 public static final 필드로 공개해도 좋다.(99P 중간) 여기서 추상 개념을 완성하는데 꼭 필요한 상수가 어떤게 있는지 궁금합니다.

**Comment by epicblues** [comment]
1.  (공개 API를 바꾸지 않는 전제로)  한 컴포넌트의 내부 구현을 수정해도 그 컴포넌트에 의존하고 있는 다른 컴포넌트들에 코드에 영향을 미치지 않기 때문에, 개발자들은 각 컴포넌트들의 내부 구현을 병렬적으로 수정할 수 있다고 해석했습니다!

2. 다른 패키지의 클라이언트들이 다른 package-private에 있는 클래스의 api를 직접 사용하는 것이 아니기 때문에
(즉 그 기능을 public 으로 공개된 같은 패키지 내에 있는 다른 공개 클래스를 통해 간접적으로 사용), package-private의 변경의 파급 효과가 같은 패키지 내에 있는 클래스에 한정된다(?)고 생각했습니다. 사실상 위 답변과 같은 의미로 봤습니다. 

3. 이 부분은 잘 모르겠습니다!

**Comment by Leeyerimearth** [comment]
1. 예를들어 인터페이스 껍데기를 만들어 놓으면, 구현체를 개발하는 쪽과 인터페이스를 가져다 쓰는 클라이언트 쪽이 병렬로 개발을 할 수 있다고 해석했습니다.
   **ex)** 껍데기 인터페이스 안에 선언된 메서드들이 매개변수와 리턴값만 정해져 있으면, 인터페이스의 구현체가 아직 만들어지지 않은 상태여도 (혹은 어떻게 구현되고있는지 몰라도) 인터페이스를 가져다쓰는 클라이언트 쪽에서는 개발이 가능합니다. 
  즉 A개발자가 ㄱ클래스를 만든 후에야 B개발자가 가져다 쓸수있는게 아니라 중간에 인터페이스 껍데기만 만들어놓고 A개발자는 구현체를 개발하고 B개발자는 가져다 쓰는 클라이언트 영역을 병렬로(=동시에) 개발할 수 있음.
  
2. - 내부구현 (= 해당 패키지 안에서만 가져다 쓴다.) 따라서 패키지안에서 지지고 볶고 변경해도 밖에서 API로 가져다 쓰지 않기때문에 내부에서 얼마든지 수정가능함.
    - 하위호환 : public API가 수정이 되면 그건 버전이 +1(+0.1 or 0.0.1 이든지요..ㅎㅎ) 이 되는건데, 클라이언트들은 이미 해당 API를 가져다 쓰고있기때문에 하위버전을 쓰고있는 것 입니다. 즉 하위호환성이란 public API가 수정이 되어도(버전 업그레이드 되어도) 이전껄 쓰고있던 클라이언트쪽에서는 잘 동작되어야한다는 것을 뜻하는것 같습니다. 
따라서 하위 호환을 위해 영원히 관리해줘야한다는 것은 public 으로 해버리면 수정할 때마다(혹은 수정 전에) 가져다 쓰는 클라이언트 쪽에서 잘 돌아가나?? 이걸 계속 신경써줘야한다는 뜻으로 이해했습니다.

**Comment by kimziou77** [comment]
3. Boolean 클래스 하나 긁어왔습니다
이런 예시가 있지 않을까요? 🧐
```java
public final class Boolean implements java.io.Serializable,  Comparable<Boolean>{

    public static final Boolean TRUE = new Boolean(true);
    public static final Boolean FALSE = new Boolean(false);
```
